spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/user-db?authSource=admin

grpc:
  server:
    port: 9090

logging:
  level:
    root: INFO
    com.nbt: DEBUG
