# -------------------------------------------------------------------------------------------------
# Ingestion Layer: AWS IoT Core setup
# -------------------------------------------------------------------------------------------------

# IoT Thing Type
resource "aws_iot_thing_type" "vehicle" {
  name = "AntigravityVehicle"
  
  properties {
    description = "Thing type for vehicles emitting telemetry and biometric data"
    searchable_attributes = ["fleet_id", "model"]
  }
}

# IoT Certificate (Used for initial provisioning, or generated by devices via JITP)
resource "aws_iot_certificate" "cert" {
  active = true
}

# Minimum-Privilege IoT Policy
data "aws_iam_policy_document" "iot_policy_doc" {
  statement {
    effect    = "Allow"
    actions   = ["iot:Connect"]
    resources = ["arn:aws:iot:${var.aws_region}:${data.aws_caller_identity.current.account_id}:client/$${iot:Connection.Thing.ThingName}"]
  }
  statement {
    effect    = "Allow"
    actions   = ["iot:Publish"]
    resources = ["arn:aws:iot:${var.aws_region}:${data.aws_caller_identity.current.account_id}:topic/antigravity/telemetry/$${iot:Connection.Thing.ThingName}"]
  }
}

resource "aws_iot_policy" "vehicle_policy" {
  name   = "AntigravityVehicleIoTAuthPolicy"
  policy = data.aws_iam_policy_document.iot_policy_doc.json
}

# Attach policy to certificate
resource "aws_iot_policy_attachment" "att" {
  policy = aws_iot_policy.vehicle_policy.name
  target = aws_iot_certificate.cert.arn
}

# IoT Rule -> Kinesis Data Stream
resource "aws_iot_topic_rule" "route_to_kinesis" {
  name        = "RouteTelemetryToKinesis"
  description = "Routes incoming MQTT telemetry to Kinesis"
  enabled     = true
  sql         = "SELECT * FROM 'antigravity/telemetry/+'"
  sql_version = "2016-03-23"

  kinesis {
    role_arn   = aws_iam_role.iot_kinesis_role.arn
    stream_name = aws_kinesis_stream.telemetry_stream.name
    partition_key = "$${topic(3)}" # Uses ThingName as partition key
  }
}
