replicaCount: 1

image:
  repository: nbt/subscription-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9093

mongodb:
  uri: mongodb://admin:password@nbt-mongo:27017/subscription-db?authSource=admin
