spring:
  application:
    name: catalog-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/catalog-db?authSource=admin

grpc:
  server:
    port: 9092

logging:
  level:
    root: INFO
